spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    #password: ${REDIS_PASSWORD:}
    lettuce:
      pool:
        max-active: 300
  zipkin:
    enabled: true
    sender:
      type: rabbit
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true
  #jwt密码
  security:
    oauth2:
      jwt:
        signingKey: 123456
  cloud:
    gateway:
      default-filters:
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY
      routes:
        - id: zeus-basic
          uri: lb://zeus-basic
          predicates:
            - Path=/zeus-basic/**
          filters:
            - StripPrefix= 1
        - id: zeus-user
          uri: lb://zeus-user
          predicates:
            - Path=/zeus-user/**
          filters:
            - StripPrefix= 1
        - id: zeus-account
          uri: lb://zeus-account
          predicates:
            - Path=/zeus-account/**
          filters:
            - StripPrefix= 1
feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true

#网关白名单，无需要签权url
gate:
  ignore:
    authentication:
      startWith: /oauth,/open,/v2/api-docs,/app

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.twelveolympians.zeus: debug
    com.jalja.org.spring: debug
  path: logs/
  file:
    max-size: 1GB